baseURL = "https://jdvalenzuelah.github.io/anova-wiki"
languageCode = "en-us"
title = "Anova WIKI"
theme = "hugo-notepadium"

[params]
dateFormat = "Lunes, Enero 2, 2006" 

[params.math]
enable = true
use = "mathjax"